name: Weekly npm dependencies update

on:
  schedule:
    - cron: '0 0 * * 1' # 毎週月曜日の深夜に実行
  workflow_dispatch: # 手動トリガーを有効化

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js 22のセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Node.js 22を指定

      # npm 依存関係を更新
      - name: Update npm dependencies
        run: |
          npm install
          npm update

      # 変更がある場合、コミットとプルリクエストを作成
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: npm-update-${{ github.run_id }}
          title: Weekly npm update
          body: |
            This PR updates npm dependencies to their latest versions.
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[create-pull-request] automated change"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: false
          draft: false
